# 🐼 Pandas - Class 11: Advanced Tricks & Performance
Welcome to **Class 11** of our Pandas series. Today we’ll explore advanced techniques to write efficient, clean, and optimized Pandas code.

## 1. Applying Custom Functions with `apply()` / `map()`
- `apply()` lets you apply a custom function across rows or columns.
- `map()` is for applying functions element-wise to a Series.
- Both are handy for transformations, calculations, and cleaning data.

In [8]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Saurabh", "Amit", "Neha", "Raj", "Priya"],
    "Science": [85, 78, 92, 74, 88],
    "Math": [90, 82, 89, 70, 25]
}

df = pd.DataFrame(data)

df['Total Marks'] = df[['Science','Math']].apply(lambda row : row.sum(),axis=1)
df

      Name  Science  Math  Total Marks
0  Saurabh       85    90          175
1     Amit       78    82          160
2     Neha       92    89          181
3      Raj       74    70          144
4    Priya       88    25          113

In [11]:
col_mean = df[['Science','Math']].apply(lambda col : col.mean())
col_mean

def to_grade(s):
    if s>90:
        return "A"
    elif s>70:
        return "B"
    elif s>40:
        return "C"
    else:
        return "F"
    
df['Math Grade'] = df['Math'].apply(to_grade)
df['Science Grade'] = df['Science'].apply(to_grade)
df['Name'] = df['Name'].map(str.lower)
df

      Name  Science  Math  Total Marks Math Grade Science Grade
0  saurabh       85    90          175          B             B
1     amit       78    82          160          B             B
2     neha       92    89          181          B             A
3      raj       74    70          144          C             B
4    priya       88    25          113          F             B