# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [18]:

import pandas as pd
# 1. Build a DataFrame with columns: Name, Age, City, Score

data = {
    "Name":['saurabh','gaurav','pavan','vikash','vijay'],
    "Age":[20,25,30,28,32],
    "City":['Pune','Delhi','Rewa','Mumbai','Banglore'],
    "Score":[90,95,80,60,30]
}
df = pd.DataFrame(data)
df['Age'] > 25
df[df['Score'] == 95]

df[(df['Age']>25) | (df['Score'] != 40) & (df['City'] != 'Pune' ) ]
df[~(df['Age']>25)]

      Name  Age   City  Score
0  saurabh   20   Pune     90
1   gaurav   25  Delhi     95

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [19]:
df.query('Score >=85')

      Name  Age   City  Score
0  saurabh   20   Pune     90
1   gaurav   25  Delhi     95

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [ ]:
# `df['Name'].str.lower()`
# df['City'].str.upper()
# df['Name'].str.replace('gaurav','gamer')
# df['City'].str.endswith("a")
# df['City'].str.startswith("R")
# df['Name'].str.contains('saurabh')

0    saurabh
1     gaurav
2      pavan
3     vikash
4      vijay
Name: Name, dtype: object

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [11]:


import pandas as pd
# 1. Build a DataFrame with columns: Name, Age, City, Score

data = {
    "Name":['saurabh','gaurav','pavan','vikash','vijay'],
    "Age":[20,25,30,28,32],
    "City":['Pune','Delhi','Rewa','Mumbai','Banglore'],
    "Score":[90,95,80,60,30]
}
df = pd.DataFrame(data)
# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

print(df[df['Age']>25])

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

print(df[(df['City']=='Mumbai')|(df['City'] == 'Delhi')])

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

print(df.query("Score >= 85 and Age <35"))

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here
df['City'] = df['City'].str.lower()
print(df['City'].str.replace('delhi','New Delhi'))

     Name  Age      City  Score
2   pavan   30      Rewa     80
3  vikash   28    Mumbai     60
4   vijay   32  Banglore     30
     Name  Age    City  Score
1  gaurav   25   Delhi     95
3  vikash   28  Mumbai     60
      Name  Age   City  Score
0  saurabh   20   Pune     90
1   gaurav   25  Delhi     95
0         pune
1    New Delhi
2         rewa
3       mumbai
4     banglore
Name: City, dtype: object

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.