# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [3]:
import pandas as pd

data = {
    "Name": [
        "Saurabh", "Gaurav", "Amit", "Raj", "Neha",
        "Priya", "Rohit", "Ankit", "Pooja", "Vikas",
        "Karan", "Simran", "Deepak", "Nisha", "Arjun",
        "Meena", "Rahul", "Sneha", "Yash", "Tina"
    ],
    "Age": [
        22, 24, 21, 23, 25,
        26, 27, 22, 24, 28,
        29, 23, 30, 21, 26,
        27, 25, 24, 23, 22
    ],
    "Department": [
        "IT", "HR", "Finance", "Marketing", "IT",
        "HR", "Finance", "Marketing", "IT", "HR",
        "Finance", "Marketing", "IT", "HR", "Finance",
        "Marketing", "IT", "HR", "Finance", "Marketing"
    ],
    "Salary": [
        20000, 30000, 10000, 40000, 35000,
        28000, 45000, 22000, 32000, 38000,
        50000, 26000, 55000, 18000, 42000,
        36000, 34000, 29000, 31000, 27000
    ]
}

df = pd.DataFrame(data)

print(df[df['Department'] == 'IT']['Salary'].mean())

35200.0

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

In [4]:
df.groupby("Department")["Salary"].mean()

Department
Finance      35600.0
HR           28600.0
IT           35200.0
Marketing    30200.0
Name: Salary, dtype: float64

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [5]:
df.groupby("Department").agg({
    "Salary":['mean','max'],
    "Age":['min','max']
})

             Salary        Age
               mean    max min max
Department
Finance     35600.0  50000  21  29
HR          28600.0  38000  21  28
IT          35200.0  55000  22  30
Marketing   30200.0  40000  22  27

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [11]:
df.pivot_table(values="Salary", index="Department", aggfunc="count")
pd.crosstab(df["Age"], df["Department"])

Department  Finance  HR  IT  Marketing
Age
21                1   1   0          0
22                0   0   1          2
23                1   0   0          2
24                0   2   1          0
25                0   0   2          0
26                1   1   0          0
27                1   0   0          1
28                0   1   0          0
29                1   0   0          0
30                0   0   1          0

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [24]:

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City
import pandas as pd

data = {
    "Department": ["HR", "IT", "Sales", "IT", "HR", "Finance", "IT", "Management"],
    "Employee": ["Saurabh", "Amit", "Rohit", "Neha", "Priya", "Karan", "Vikas", "Anjali"],
    "Salary": [25000, 40000, 35000, 42000, 28000, 37000, 45000, 30000],
    "Age": [24, 28, 26, 30, 25, 29, 31, 27],
    "City": ["Pune", "Mumbai", "Delhi", "Pune", "Mumbai", "Delhi", "Pune", "Mumbai"]
}

df = pd.DataFrame(data)

print(df)

# 2. Group by Department to get average Salary and max Age
# Write your code here

df.groupby("Department").agg({
    "Salary":'mean',
    'Age':'max'
})

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
# Write your code here

df.groupby("Department").agg({
    "Salary": ["mean", "max", "min"],
    "Age": ["max", "min"]
})

# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here

df.pivot_table(values="Salary",index="Department",columns="City", aggfunc="min")

# 5. Build a crosstab for Department vs City
# Write your code here

# pd.crosstab(df["Department"], df["City"])

   Department Employee  Salary  Age    City
0          HR  Saurabh   25000   24    Pune
1          IT     Amit   40000   28  Mumbai
2       Sales    Rohit   35000   26   Delhi
3          IT     Neha   42000   30    Pune
4          HR    Priya   28000   25  Mumbai
5     Finance    Karan   37000   29   Delhi
6          IT    Vikas   45000   31    Pune
7  Management   Anjali   30000   27  Mumbai

City          Delhi   Mumbai     Pune
Department
Finance     37000.0      NaN      NaN
HR              NaN  28000.0  25000.0
IT              NaN  40000.0  42000.0
Management      NaN  30000.0      NaN
Sales       35000.0      NaN      NaN

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.